# See https://redoc.ly/docs/cli/configuration/ for more information.
extends:
  - recommended

apis:
  core@v2:
    root: ./api_src/root.yaml
    rules:
      no-unused-components: warn

theme:
  openapi:
    htmlTemplate: ./docs/template.html
    hideDownloadButton: true
    expandDefaultServerVariables : true # nice for debugging
    expandResponses: all # nice for debugging
    expandSingleSchemaField: true # nice for debugging
    jsonSampleExpandLevel: all # nice for debugging
    hideSchemaTitles: true
    requiredPropsFirst: true
    theme:
      spacing:
        sectionVertical: 10
      colors:
        primary:
          main: "#e90000"
