openapi: 3.0.2
info:
  version: 1.12.1
  title: PodcastIndex.org API
  termsOfService: 'https://github.com/Podcastindex-org/legal/blob/main/TermsOfService.md'
  contact:
    email: info@podcastindex.org
    url: 'https://podcastindex.org/'
  license:
    name: MIT
    url: 'https://github.com/Podcastindex-org/docs-api/blob/master/LICENSE'
  x-logo:
    url: 'logo.svg'
    href: '/'
  # language=Markdown
  description: |
    Download the openapi spec in [json](pi_api.json) or [yaml](pi_api.yaml) format.

    # Overview

    The Podcast Index (Podcast Index LLC) is a software developer focused partnership that provides tools and data to
    anyone who aspires to create new and exciting Podcast experiences without the heavy lifting of indexing,
    aggregation and data management.

    # Example Code

    Users have provided example code for working the API in the following languages:

      - [AWS Lambda - python](https://github.com/tbowers/python-podcastindex-org-lambda)
      - [Bash](https://github.com/suorcd/Bash-podcastindex-org-example)
      - [C#](https://github.com/ComicStrip/csharp-podcastindex-org-example)
      - [Elisp](https://github.com/sabexx/elisp-example)
      - [Flutter/Dart](https://github.com/crediblecreative/flutter-dart-podcastindex-org-example)
      - [Go](https://github.com/ComicStrip/Go-podcastindex-org-example)
      - [Go](https://github.com/kilobit/podcast-index-client)
      - [Java](https://github.com/ComicStrip/Java-podcastindex-org-example)
      - [Java](https://github.com/stucoates/PodcastIndexJavaClient)
      - [Node.js](https://github.com/ComicStrip/node.js-podcastindex-org-example)
      - [PHP](https://github.com/Podcastindex-org/example-code)
      - [Python](https://github.com/tbowers/python-podcastindex-org-example)
      - [Swift](https://github.com/ComicStrip/Swift-podcastindex-org-example)
      - ... [More](https://github.com/Podcastindex-org-Examples)

    Don't see your desired language, create an example repo and create a
    [Pull Request](https://github.com/Podcastindex-org/docs-api/pulls) with a link to your example code project!

    # Libraries

    User created libraries for working with the API:

      - Java
          - [podcast4j](https://github.com/yusufyilmazfr/podcast4j)
      - .NET
          - [PodcastIndexSharp](https://www.nuget.org/packages/PodcastIndexSharp)
      - Node.js/npm/yarn
          - [podcast-index-api](https://www.npmjs.com/package/podcast-index-api)
          - [podcastdx-client](https://www.npmjs.com/package/podcastdx-client)
      - PHP
          - [podcastindex-php](https://github.com/LowSociety/podcastindex-php)
      - Python/pip
          - [python-podcastindex](https://pypi.org/project/python-podcastindex/)
      - R
          - [podindexr](https://github.com/rpodcast/podindexr)
      - Ruby
          - [podcast-index](https://github.com/jasonyork/podcast-index)
      - Swift
          - [PodcastIndexKit](https://github.com/SparrowTek/PodcastIndexKit)
      - Kotlin
          - [PodcastIndex-SDK](https://github.com/mr3y-the-programmer/PodcastIndex-SDK)

    Are we missing a library? Did you create one for a different language? Create a
    [Pull Request](https://github.com/Podcastindex-org/docs-api/pulls) with a link to the new library!

    # Postman

    A collection file for use in the [Postman](https://www.postman.com/) application is available for this API.

      1. Download the contents of the [Postman Docs](https://github.com/Podcastindex-org/docs-api/tree/master/Postman%20Docs) folder.
      2. Import the `PodcastIndex.postman_collection.json` collection to Postman
      3. Import the `PodcastIndexOrgEnvironment.postman_environment.json` to Postman
      4. Click "Environments" on the left sidebar
      5. Select the checkbox next to the PodcastIndexOrgEnvironment entry
      6. Set `AuthKey` and `SeceretKey` values under the "Current Value" column using your API information
      7. Click "Collections" from the sidebar
      8. Select PodcastIndex
      9. Select and run the endpoint to test

    # Contributing

    The source for this API documentation is available at
    [https://github.com/Podcastindex-org/docs-api](https://github.com/Podcastindex-org/docs-api).
    Submit an Issue or create a Pull Request.

    # Authentication Details

    Sending an API request is easy. We use an Amazon-style request authorization token to secure each request.


    Register for a free API key at https://api.podcastindex.org/


    These headers parameters are required for each request: `User-Agent`, `X-Auth-Date`, `X-Auth-Key`, `Authorization`


    See [Authentication](#auth) for description of parameters.

    # Legal

    Legal

      - [Privacy Policy](https://github.com/Podcastindex-org/legal/blob/main/PrivacyPolicy.md)
      - [Terms of Service](https://github.com/Podcastindex-org/legal/blob/main/TermsOfService.md)
      - [License](https://github.com/Podcastindex-org/docs-api/blob/master/LICENSE)

tags:
  - name: Search
    # language=Markdown
    description: |
      Search the index
  - name: Podcasts
    # language=Markdown
    description: |
      Find details about a Podcast and its feed.
  - name: Episodes
    # language=Markdown
    description: |
      Find details about one or more episodes of a podcast or podcasts.
  - name: Recent
    # language=Markdown
    description: |
      Find recent additions to the index
  - name: Value
    # language=Markdown
    description: |
      The podcast's "Value for Value" information
  - name: Stats
    # language=Markdown
    description: |
      Statistics for items in the Podcast Index
  - name: Categories
    # language=Markdown
    description: |
      Categories used by the Podcast Index
  - name: Hub
    # language=Markdown
    description: |
      Notify the index that a feed has changed
  - name: Add
    # language=Markdown
    description: |
      Add new podcast feeds to the index.


      **NOTE**: To add to the index, the API Key must have write or publisher permissions.
servers:
  - url: 'https://api.podcastindex.org/api/1.0'
components:
  securitySchemes:
    User-Agent:
      $ref: 'components/securitySchemes/User-Agent.yaml'
    API-Key:
      $ref: 'components/securitySchemes/API-Key.yaml'
    Date:
      $ref: 'components/securitySchemes/Date.yaml'
    Authorization:
      $ref: 'components/securitySchemes/Authorization.yaml'
paths:
  '/search':
    $ref: 'paths/itunes/search.yaml'
  '/lookup':
    $ref: 'paths/itunes/lookup.yaml'
  '/search/byterm':
    $ref: 'paths/search/byterm.yaml'
  '/search/bytitle':
    $ref: 'paths/search/bytitle.yaml'
  '/search/byperson':
    $ref: 'paths/search/byperson.yaml'
  '/search/music/byterm':
    $ref: 'paths/search/music/byterm.yaml'
  '/podcasts/byfeedid':
    $ref: 'paths/podcasts/byfeedid.yaml'
  '/podcasts/byfeedurl':
    $ref: 'paths/podcasts/byfeedurl.yaml'
  '/podcasts/byitunesid':
    $ref: 'paths/podcasts/byitunesid.yaml'
  '/podcasts/byguid':
    $ref: 'paths/podcasts/byguid.yaml'
  '/podcasts/bytag':
    $ref: 'paths/podcasts/bytag.yaml'
  '/podcasts/bymedium':
    $ref: 'paths/podcasts/bymedium.yaml'
  '/podcasts/trending':
    $ref: 'paths/podcasts/trending.yaml'
  '/podcasts/dead':
    $ref: 'paths/podcasts/dead.yaml'
  '/podcasts/batch/byguid':
    $ref: 'paths/podcasts/batch/byguid.yaml'
  '/episodes/byfeedid':
    $ref: 'paths/episodes/byfeedid.yaml'
  '/episodes/byfeedurl':
    $ref: 'paths/episodes/byfeedurl.yaml'
  '/episodes/bypodcastguid':
    $ref: 'paths/episodes/bypodcastguid.yaml'
  '/episodes/byitunesid':
    $ref: 'paths/episodes/byitunesid.yaml'
  '/episodes/byid':
    $ref: 'paths/episodes/byid.yaml'
  '/episodes/byguid':
    $ref: 'paths/episodes/byguid.yaml'
  '/episodes/live':
    $ref: 'paths/episodes/live.yaml'
  '/episodes/random':
    $ref: 'paths/episodes/random.yaml'
  '/recent/episodes':
    $ref: 'paths/recent/episodes.yaml'
  '/recent/feeds':
    $ref: 'paths/recent/feeds.yaml'
  '/recent/newfeeds':
    $ref: 'paths/recent/newfeeds.yaml'
  '/recent/newvaluefeeds':
    $ref: 'paths/recent/newvaluefeeds.yaml'
  '/recent/data':
    $ref: 'paths/recent/data.yaml'
  '/recent/soundbites':
    $ref: 'paths/recent/soundbites.yaml'
  '/value/byfeedid':
    $ref: 'paths/value/byfeedid.yaml'
  '/value/byfeedurl':
    $ref: 'paths/value/byfeedurl.yaml'
  '/value/bypodcastguid':
    $ref: 'paths/value/bypodcastguid.yaml'
  '/value/byepisodeguid':
    $ref: 'paths/value/byepisodeguid.yaml'
  '/value/batch/byepisodeguid':
    $ref: 'paths/value/batch/byepisodeguid.yaml'
  '/stats/current':
    $ref: 'paths/stats/current.yaml'
  '/categories/list':
    $ref: 'paths/categories/list.yaml'
  '/hub/pubnotify':
    $ref: 'paths/hub/pubnotify.yaml'
  '/add/byfeedurl':
    $ref: 'paths/add/byfeedurl.yaml'
  '/add/byitunesid':
    $ref: 'paths/add/byitunesid.yaml'
  '/static/stats/daily_counts.json':
    $ref: 'paths/static/stats/daily_counts.yaml'
  '/static/stats/hourly_counts.json':
    $ref: 'paths/static/stats/hourly_counts.yaml'
  '/static/stats/chart-data.json':
    $ref: 'paths/static/stats/v4v.yaml'
  '/static/stats/v4vmusic.json':
    $ref: 'paths/static/stats/music_json.yaml'
  '/static/stats/v4vmusic.opml':
    $ref: 'paths/static/stats/music_opml.yaml'
  '/static/stats/v4vmusic.rss':
    $ref: 'paths/static/stats/music_rss.yaml'
  '/static/tracking/current':
    $ref: 'paths/static/tracking/current.yaml'
  '/static/tracking/feedValueBlocks':
    $ref: 'paths/static/tracking/feedValueBlocks.yaml'
  '/static/tracking/episodeValueBlocks':
    $ref: 'paths/static/tracking/episodeValueBlocks.yaml'
  '/static/public/podcastindex_dead_feeds.csv':
    $ref: 'paths/static/public/podcastindex_dead_feeds.yaml'
  '/static/public/podcastindex_feeds.db.tgz':
    $ref: 'paths/static/public/podcastindex_feeds_db.yaml'
  # currently not used and has some bugs. leaving off for now
  #'/add/batch/byfeedurl':
  #  $ref: 'paths/add/batch/byfeedurl.yaml'
