name: Lint API Docs
on: [push, pull_request]
jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
            node-version-file: '.nvmrc'
            cache: "yarn"

      - name: Install project dependencies
        run: yarn

      - name: Run Lint
        run: yarn run build

      - name: Run Lint
        run: yarn run lint
